# Generated by Django 3.2.4 on 2021-06-11 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
                ('category_image', models.FileField(blank=True, null=True, upload_to='upload')),
                ('category_description', models.TextField(blank=True, max_length=255, null=True)),
                ('category_status', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Category_Name',
            },
        ),
    ]
