# Generated by Django 3.2.4 on 2021-06-14 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
                ('category_image', models.FileField(blank=True, null=True, upload_to='upload')),
                ('category_description', models.TextField(blank=True, max_length=255, null=True)),
                ('category_status', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Category',
            },
        ),
        migrations.CreateModel(
            name='ProductRecommend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=250)),
                ('product_description', models.TextField(blank=True, max_length=255, null=True)),
                ('product_price', models.FloatField(default=0)),
                ('product_recommend', models.BooleanField(default=False)),
                ('product_status', models.BooleanField(default=False)),
                ('product_created', models.DateTimeField(auto_now_add=True)),
                ('product_updated', models.DateTimeField(auto_now=True)),
                ('product_category', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cactusshop.category')),
            ],
            options={
                'verbose_name_plural': 'Product_Recommend',
            },
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(upload_to='products/')),
                ('post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cactusshop.productrecommend')),
            ],
        ),
    ]
