# Generated by Django 3.2.4 on 2021-06-15 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cactusshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productrecommend',
            options={'verbose_name_plural': 'Product'},
        ),
    ]
