# Generated by Django 3.2.4 on 2021-06-17 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cactusshop', '0003_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='description',
            new_name='message',
        ),
    ]
