# Generated by Django 3.2.4 on 2021-06-19 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cactusshop', '0005_alter_productrecommend_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, max_length=500, null=True)),
                ('rating', models.IntegerField(default=0)),
                ('product_comment', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cactusshop.productrecommend')),
            ],
        ),
    ]
