# Generated by Django 3.2.4 on 2021-06-19 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cactusshop', '0006_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='product_comment',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='cactusshop.productrecommend'),
        ),
    ]
